### ISSUE TITLE
ValueError: Expecting Object

### ISSUE THREAD

**Issue by Mustyy** [ujwlkarn/Twitter-Sentiment-Analysis#1]
Traceback (most recent call last):
  File "term_sentiment.py", line 72, in <module>
    main()
  File "term_sentiment.py", line 35, in main
    data=json.loads(line)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting object: line 1 column 3283 (char 3282)

**Comment by ujjwalkarn** [comment]
@Mustyy sorry for the trouble, the tutorial and the code in this repository is pretty old and is not supported anymore. I would recommend using newer tutorials available on the web in case you want to try sentiment analysis on Twitter data.
